version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: doc/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
